//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfJsonRestService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDICOMStudy
    {
        public int Id1 { get; set; }
        public string C00100010 { get; set; }
        public string C00100020 { get; set; }
        public string C00100021 { get; set; }
        public Nullable<System.DateTime> C00100030 { get; set; }
        public string C00100040 { get; set; }
        public Nullable<System.DateTime> C00080020 { get; set; }
        public Nullable<System.DateTime> C00080030 { get; set; }
        public string C00080050 { get; set; }
        public string C00200010 { get; set; }
        public string C0020000D { get; set; }
        public string C00201000 { get; set; }
        public string C00080090 { get; set; }
        public string C00080061 { get; set; }
        public string C00101000 { get; set; }
        public string C00081030 { get; set; }
        public string C00081050 { get; set; }
        public string C00081060 { get; set; }
        public string C00080080 { get; set; }
        public string C00081010 { get; set; }
        public string C00081040 { get; set; }
        public string C0032000A { get; set; }
        public string C00321030 { get; set; }
        public string C00081032 { get; set; }
        public System.DateTime DateLastAccessed { get; set; }
        public Nullable<int> StudyState { get; set; }
        public Nullable<int> StudyIdLibrary { get; set; }
        public Nullable<int> AggregateCount2_1 { get; set; }
        public Nullable<int> AggregateCount3_1 { get; set; }
        public Nullable<int> AggregateCountNotRejected3_1 { get; set; }
        public Nullable<int> StudyMediumState { get; set; }
        public Nullable<System.DateTime> FirstArchiveDate { get; set; }
        public System.DateTime DateLastStudyModification { get; set; }
        public System.DateTime DateLastFileChange { get; set; }
        public System.DateTime DateTimeFileLockExpiration { get; set; }
        public Nullable<bool> StudyHidden { get; set; }
        public string SortedModalities { get; set; }
    }
}
